version: "3.8"

services:
  # Config Server
  configsvr:
    image: mongo:7.0
    command: --configsvr --replSet configReplSet --port 27017 --bind_ip_all
    container_name: configsvr
    ports:
      - 27017:27017
    volumes:
      - configsvr:/data/db

  # Shards:
  shard1:
    image: mongo:7.0 
    command: --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    container_name: shard1
    ports:
      - 27018:27018
    volumes:
      - shard1:/data/db

  shard2:
    image: mongo:7.0
    command: --shardsvr --replSet shard2ReplSet --port 27019 --bind_ip_all
    container_name: shard2
    ports:
      - 27019:27019
    volumes:
      - shard2:/data/db

  shard3:
    image: mongo:7.0
    command: --shardsvr --replSet shard3ReplSet --port 27021 --bind_ip_all
    container_name: shard3
    ports:
      - 27021:27021
    volumes:
      - shard3:/data/db
  
  shard4:
    image: mongo:7.0
    command: --shardsvr --replSet shard4ReplSet --port 27022 --bind_ip_all
    container_name: shard4
    ports:
      - 27022:27022
    volumes:
      - shard4:/data/db

  # Mongos Router
  mongos:
    image: mongo:7.0
    container_name: mongos
    depends_on:
      - configsvr
      - shard1
      - shard2
      - shard3
      - shard4
    command: >
      mongos --configdb configReplSet/configsvr:27017 --bind_ip_all --port 27020
    ports:
      - 27020:27020

volumes:
  configsvr: 
  shard1:
  shard2:
  shard3:
  shard4: